# 使用最新的 Python 版本
FROM python:3.12.1

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt torch torchvision torchaudio

# Copy the Python script into the container
COPY videoSrt.py /app/

# Run the script
CMD ["python", "videoSrt.py"]