# 使用最新的 Python 版本
FROM python:latest

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y ffmpeg

# Copy the Python script into the container
COPY convertVideoToMov.py /app/

# Run the script
CMD ["python", "convertVideoToMov.py"]