version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    container_name: server-app
