version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./practice:/app/practice
    container_name: server-app
