# 使用最新的 Node.js 版本
FROM node:22

# 設定工作目錄為 /app
WORKDIR /app

# 複製 package.json 和 package-lock.json 來安裝依賴
COPY package.json package-lock.json ./
RUN npm install --no-audit

# 複製其他文件，並排除 .env
COPY . .

# 設置 NODE_PATH 環境變量
ENV NODE_PATH=/app/node_modules

# 曝露應用的端口
EXPOSE 8080

# 將 NODE_PATH 添加到 .bashrc
RUN echo "export NODE_PATH=/app/node_modules" >> /root/.bashrc


CMD ["node", "/app/backend/server.js"]
