# docker-compose.yml
version: "3.8"

services:
  video_srt_service:
    build:
      context: .
      dockerfile: videoSrt.Dockerfile
    restart: always # Auto-restart on failure
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true # Keep stdin open to accept Y/N inputs
    tty: true # Allocate a pseudo-TTY
    env_file:
      - ../.env

  convert_video_service:
    build:
      context: .
      dockerfile: convertVideoToMov.Dockerfile
    restart: always # Auto-restart on failure
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true # Keep stdin open to accept Y/N inputs
    tty: true # Allocate a pseudo-TTY
    env_file:
      - ../.env
